### ISSUE TITLE
Лайфхак

### ISSUE THREAD

**Issue by PashaWNN** [CheeryLee/blender_apply_modifiers#2]
Вряд ли ещё актуально, но я наткнулся на спобоб, описанный ниже, когда гуглил, как применить все модификаторы через API, когда хотел написать себе такой же аддон.

Оказывается, самый простой способ сделать то же самое, что делает этот аддон — прожать Object -> Convert -> Mesh.

**Comment by CheeryLee** [comment]
Аддон писался, когда версия 2.79 проживала свои лучшие времена, поэтому он действительно более не актуален. 🙂
